repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        -   id: check-yaml
            exclude: ^migrations/
        -   id: end-of-file-fixer
            exclude: ^migrations/
        -   id: trailing-whitespace
            exclude: ^migrations/
  -   repo: https://github.com/psf/black
      rev: 21.11b1
      hooks:
        -   id: black
            exclude: ^/migrations/
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
