version: '3.8'

services:
  web:
    build: .
    command: "gunicorn nonic.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - ".env"
    volumes:
      - "static_volume:/home/app/web/staticfiles"
      - "media_volume:/home/app/web/mediafiles"
    depends_on:
      - "postgres"
  postgres:
    env_file:
      - ".env"
    image: "postgres:13.3"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  nginx:
    build:
      context: "nginx"
      dockerfile: "Dockerfile"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "static_volume:/home/app/web/staticfiles"
      - "media_volume:/home/app/web/mediafiles"
    depends_on:
      - "web"
volumes:
  postgres_data:
  static_volume:
  media_volume: