version: '3.8'

services:
  web:
    build: .
    command: "gunicorn nonic.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - ".env"
    volumes:
      - "static_volume:/home/app/web/staticfiles"
      - "media_volume:/home/app/web/mediafiles"
    restart: always
  nginx:
    build:
      context: "nginx"
      dockerfile: "Dockerfile"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "static_volume:/home/app/web/staticfiles"
      - "media_volume:/home/app/web/mediafiles"
    depends_on:
      - "web"
    restart: always
volumes:
  static_volume:
  media_volume: