import os

BOT_NAME = "second"
SPIDER_MODULES = ["second.spiders"]
NEWSPIDER_MODULE = "second.spiders"
ROBOTSTXT_OBEY = True
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
DOWNLOAD_DELAY = 1
LOG_ENABLED = False
FEED_EXPORT_ENCODING = "utf-8"
CONCURRENT_REQUESTS = 2
CONCURRENT_REQUESTS_PER_DOMAIN = 1
CONCURRENT_REQUESTS_PER_IP = 1
RETRY_ENABLED = True
RETRY_TIMES = 3
RETRY_HTTP_CODES = [500, 503, 504, 400, 403, 404, 408]
manufacture_url = os.getenv("MANUFACTURE_URL")
s1_phrase = os.getenv("S1_PHRASE")
second_base_url = os.getenv("SECOND_BASE_URL")
start_urls_second = os.getenv("START_URL_SECOND").split(",")
LOG_LEVEL = "ERROR"
