from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


BOT_NAME = "second"
SPIDER_MODULES = ["second.spiders"]
NEWSPIDER_MODULE = "second.spiders"
ROBOTSTXT_OBEY = True
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
DOWNLOAD_DELAY = 1
LOG_ENABLED = False
FEED_EXPORT_ENCODING = "utf-8"
CONCURRENT_REQUESTS = 2
CONCURRENT_REQUESTS_PER_DOMAIN = 1
CONCURRENT_REQUESTS_PER_IP = 1
RETRY_ENABLED = True
RETRY_TIMES = 3
RETRY_HTTP_CODES = [500, 503, 504, 400, 403, 404, 408]
