# Generated by Django 3.2.4 on 2021-07-27 16:51
import django.db.models.deletion
from django.db import migrations, models

import nonic.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Beer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("code", models.CharField(max_length=255, verbose_name="Code")),
                ("description", models.TextField(verbose_name="Description")),
                ("volume", models.PositiveSmallIntegerField(blank=True, default=500, verbose_name="Volume (ml)")),
                ("alcohol", models.FloatField(blank=True, null=True, verbose_name="Alcohol  %")),
                ("extract", models.FloatField(blank=True, null=True, verbose_name="Extract")),
                ("tags", models.JSONField(blank=True, default=dict, verbose_name="Tags")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=nonic.storages.PublicMediaStorage(),
                        upload_to="",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "manufactured_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beers",
                        to="nonic.manufacturer",
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "style",
                    models.ManyToManyField(blank=True, related_name="beers", to="nonic.Style", verbose_name="Style"),
                ),
            ],
            options={
                "ordering": ["-name"],
            },
        ),
    ]
