# Generated by Django 3.2.6 on 2022-01-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nonic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="country",
            field=models.CharField(default="", max_length=255, verbose_name="Country"),
            preserve_default=False,
        ),
    ]
