# Generated by Django 4.0 on 2022-01-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonic', '0004_beer_rating_beer_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='manufactured_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='nonic.manufacturer', verbose_name='Manufacturer'),
        ),
    ]
