# Generated by Django 4.0 on 2022-01-31 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nonic", "0005_alter_beer_country_alter_beer_manufactured_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeerRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Rating",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="beer",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_beer", through="nonic.UserFavorite", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="beer",
            name="users_rating",
            field=models.ManyToManyField(
                related_name="beer_rating", through="nonic.BeerRating", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="beer",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                max_digits=3,
                validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)],
                verbose_name="Rating",
            ),
        ),
        migrations.AddField(
            model_name="userfavorite",
            name="beer",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="nonic.beer"),
        ),
        migrations.AddField(
            model_name="userfavorite",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user"),
        ),
        migrations.AddField(
            model_name="beerrating",
            name="beer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nonic.beer"),
        ),
        migrations.AddField(
            model_name="beerrating",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.user"),
        ),
    ]
