# Generated by Django 4.0 on 2022-02-07 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('nonic', '0006_beerrating_userfavorite_beer_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_beer', through='nonic.UserFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beer',
            name='users_rating',
            field=models.ManyToManyField(blank=True, related_name='beer_rating', through='nonic.BeerRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
