# Generated by Django 4.0 on 2022-02-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_user_otp_exp_date'),
        ('nonic', '0008_beer_favorites_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='beer',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='style',
            name='name_pl',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='BeerTemplate',
            fields=[
                ('beer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nonic.beer')),
                ('draft_created', models.DateTimeField(auto_now_add=True)),
                ('draft_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('nonic.beer',),
        ),
    ]
