import os

BOT_NAME = "first"
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
DOWNLOAD_DELAY = 1
SPIDER_MODULES = ["first.spiders"]
NEWSPIDER_MODULE = "first.spiders"
LOG_ENABLED = False
FEED_EXPORT_ENCODING = "utf-8"
ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 2
CONCURRENT_REQUESTS_PER_DOMAIN = 1
CONCURRENT_REQUESTS_PER_IP = 1
RETRY_ENABLED = True
RETRY_TIMES = 3
RETRY_HTTP_CODES = [500, 503, 504, 400, 403, 404, 408]
start_url_first = os.getenv("START_URL_FIRST")
